### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by DavidColson** [aldocd4/DerelictNANOVG#1]
Hi, I'm trying to get this working and I'm have a lot of trouble. 

I understand I need to compile Nanovg? I've tried to do this but when my d app runs and links with nanovg.dll it exclaims that nvgCreateGL3 doesn't exist. 

What are the correct steps for building Nanovg to work with this dynamic binding?

Thanks

**Comment by DavidColson** [comment]
Alright, with some fiddling I managed to make a shared library by making a stub c file in nanovg with this inside: 

```
#include <GL/glew.h>
#ifdef __APPLE__
#   define GLFW_INCLUDE_GLCOREARB
#endif
#include <GLFW/glfw3.h>
#include "nanovg.h"
#define NANOVG_GL3_IMPLEMENTATION
#include "nanovg_gl.h"
```

I also had to link glew and glfw3. That worked great

But now when I give the dll to my D app and run it I get the following message:

```
C:\Windows\SysWOW64\kernel32.dll unloaded.
C:\Windows\SysWOW64\vcruntime140d.dll unloaded.
C:\Windows\SysWOW64\ucrtbased.dll unloaded.
D:\Dev\Surface\nanovg.dll unloaded.
First-chance exception: derelict.util.exception.SharedLibLoadException Failed to load one or more shared libraries:
	nanovg.dll - The specified module could not be found. at C:\Users\David\AppData\Roaming\dub\packages\derelict-util-2.0.6\derelict-util\source\derelict\util\exception.d(35)
Unhandled exception: derelict.util.exception.SharedLibLoadException Failed to load one or more shared libraries:
	nanovg.dll - The specified module could not be found. at C:\Users\David\AppData\Roaming\dub\packages\derelict-util-2.0.6\derelict-util\source\derelict\util\exception.d(35)
```

Looks as though nanovg.dll is unloaded, then it immediately complains that it can't find it.

How do I fix this?

**Comment by aldocd4** [comment]
hi, 

maybe you compiled nanovg as a 64 bit dll ?

I can send you a working VS 2015 project tu build the dll if you want

**Comment by DavidColson** [comment]
I ended up writing an extra function to manually load the gl functions with wglGetProcAddress calls.

This did mean I had to modify the d linking code to load that as well, but it works and my nanovg dll is 175KB.

Thanks for your help though!
