### ISSUE TITLE
Building for windows

### ISSUE THREAD

**Issue by aferust** [aldocd4/DerelictNANOVG#2]
Could you please provide a cmake txt covering building process for Windows with v.studio compilers? I tried to create one but getting linking errors about glew. Any information about correct glew download links would help too.

**Comment by aldocd4** [comment]
Hello,

maybe you can try nanovg DLLs that I builded for windows here: https://github.com/evael-dev/evael/tree/master/dist ?

If that doesn't work (or if you want to build them yourself) I will give you more info about vs / glew setup.

**Comment by aferust** [comment]
thank you. I will give it a try.

**Comment by aferust** [comment]
Ok. First of all, please create a package.d file in source/derelict/nanovg/

```d
module derelict.nanovg;

public {
    import derelict.nanovg.funcs;
    import derelict.nanovg.nanovg;
    import derelict.nanovg.types;
}
```
without this I could not use any function related with the library.

I finally tried to run this code (it compiles):
```d
import std.stdio;

import derelict.nanovg;
import derelict.opengl3.gl3;

void main()
{
	DerelictGL3.reload();
	DerelictNANOVG.load();

	auto nvg = nvgCreateGL3(NVGcreateFlags.NVG_STENCIL_STROKES | NVGcreateFlags.NVG_DEBUG);
	
	writeln("Edit source/app.d to start your project.");

	nvgDeleteGL3(nvg);
}
```
But it crashes:
```cmd
Running .\denenanovg.exe 

derelict.util.exception.DerelictException@C:\Users\user\AppData\Local\dub\packages\derelict-gl3-1.0.24\derelict-gl3\source\derelict\opengl3\gl3.d(85): DerelictGL3.reload failure: An OpenGL context is not currently active.
----------------
0x00007FF6CB0C1BE4 in derelict.opengl3.gl3.DerelictGL3Loader.reload at C:\Users\user\AppData\Local\dub\packages\derelict-gl3-1.0.24\derelict-gl3\source\derelict\opengl3\gl3.d(85)
0x00007FF6CB0C1029 in app.D main at D:\projects\d_projects\denenano_\denenanovg\source\app.d(9)
0x00007FF6CB10F82D in void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll()
0x00007FF6CB10F6DE in d_run_main2
0x00007FF6CB10F4EB in d_run_main
0x00007FF6CB0C1AB7 in __entrypoint.main at D:\projects\d_projects\denenano_\denenanovg\__entrypoint.d(8)
0x00007FF6CB12D83C in __scrt_common_main_seh at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(288)
0x00007FFCD8247BD4 in BaseThreadInitThunk
0x00007FFCD83CCED1 in RtlUserThreadStart
Program exited with code 1
```

**Comment by aldocd4** [comment]
Hello,

you need to create a valid OpenGL context (with a window library, like GLFW).

Here is a sample, main.d : 
<script src="https://gist.github.com/aldocd4/067663b5e13adc596dcd9bb0bb50deb8.js"></script>

And the dub.json that use bindbc-opengl and bindbc-glfw (dont forget to take glfw.dll from evael) :
<script src="https://gist.github.com/aldocd4/af5d3555e22804983c91bae46239d6bb.js"></script>

You should see a yellow rect.

![image](https://user-images.githubusercontent.com/2823944/67422777-643af200-f5d3-11e9-8604-3fcb800f652f.png)


 Please check nanovg official code and examples if you want advanced examples. Or check old evael gui library in the 0.0.1 tag:  https://github.com/evael-dev/evael/tree/v0.0.1/source/evael/graphics/gui/controls

**Comment by aldocd4** [comment]
Try 

`glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE); `

instead of 

`glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_ANY_PROFILE);`

at line 24.

**Comment by aferust** [comment]
it caused no effect.

**Comment by aldocd4** [comment]
Ok so it means your computer is old and doesnt support opengl 3+ :(
NanoVG works with GL2 but nanovg.dll need to be recompiled.

Here is new [main.d](https://gist.github.com/aldocd4/e866e70c594cf820909a5bd04d148db2)
New [dub.json](https://gist.github.com/aldocd4/d970ff0e5481687df81d6cd554cdeb9c).

nanovg.dll 64bits attached.

[nanovg.zip](https://github.com/aldocd4/DerelictNANOVG/files/3764026/nanovg.zip)

**Comment by aferust** [comment]
it works after your changes. My laptop is lenovo Y510P (4-5 years old). Its graphic card is GeForce 755m and the specification says it supports OpenGL 4.5:
https://www.geforce.com/hardware/notebook-gpus/geforce-gt-755m/specifications

Maybe it is due to my secondary g. device which is intel HD implicitly used by default. Anyway I already made you busy a lot. I will play around it as it is.

**Comment by aldocd4** [comment]
Ok maybe try to force app to load opengl 3.1+ to work with nanovg3 if your computer supports it.

Good luck!

**Comment by aferust** [comment]
Hey opengl3.1 works! Thanks:
GLFW: glfw30
false
Opengl: gl31
