### ISSUE TITLE
bindbc.nanovg

### ISSUE THREAD

**Issue by aferust** [aldocd4/DerelictNANOVG#3]
Hi Aldo,

I converted derelict.nanovg to bindbc-nanovg, but I thought I should not create the repo. If you give me your email I can send the files to you for creating the repo. Or I can create the repo and transfer the ownership to you. I am planing to use it with my hobby gui [lib](https://github.com/aferust/noobgui). Please let me know.
I only tried it on windows with below config with success:
...
"dflags": ["-betterC"],
    "subConfigurations": {
        "bindbc-nanovg": "dynamicBC"
    },
    "versions": [
        "NanovgGL3",
        "GL_32"
    ]
...

**Comment by aldocd4** [comment]
Hello @aferust , please go ahead and create the bindbc-nanovg repo on your account. I will put a link to this new git repo and ask people to use it instead ot this one.

Thanks

**Comment by aferust** [comment]
Done! Another alternative may be arsd-official:nanovega. But it uses typeId from runtime and cannot be used with betterC
